name: Build and deploy container app to Azure Web App - sastravelplanner

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL}}
  CI: false
jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install
        run: npm i

      - name: Build
        run: npm run build

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_96ac73af7b154d18b89c4e83d062b1db }}
          password: ${{ secrets.AzureAppService_ContainerPassword_361dc17ad36d476281e2c69952c78507 }}

      - name: Build and push container image to registry
        run: |
          docker build -t fernandaasilvaa/travel-planner:${{ github.sha }} .
          docker push fernandaasilvaa/travel-planner:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sastravelplanner'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_6eed08bc14364bdc97345d979845c83c }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_96ac73af7b154d18b89c4e83d062b1db }}/fernandaasilvaa/travel-planner:${{ github.sha }}'
